const palavras = [
  "amarelar", "abanador", "amor", "abrigo", "abrir",
  "bolado", "bizarro", "birita", "biscoiteiro", "banco",
  "caixa", "cuidado", "cancelado", "carinho", "cringe",
  "dados", "disney", "danone", "dente", "diamante",
  "elefante", "esfera", "encontro", "escola", "economia",
  "fogo", "fama", "festa", "flauta",  "fotografia",
  "gelo", "grito", "goleiro", "gringo", "gatilho",
  "harmonia", "honrar", "hoje", "hiena", "hype",
  "igreja", "importante", "irado", "inferno", "idiota",
  "jantar", "jumento", "janela", "jaula", "jaleco",
  "louco", "lua", "luz", "lindo", "lacrar",
  "maneiro", "militante", "mico", "matar", "mucilon",
  "nada", "navio", "namorado", "ninja", "natal",
  "ovo", "ostra", "olhar", "ouro", "ornamento",
  "picada", "polvo", "princesa", "pizza", "patroa",
  "queijo", "quantia", "quarentena", "quadrilha", "quebrar",
  "risada", "role", "rato", "racional", "rainha",
  "salada", "sinistro", "sinuca", "serrote", "sangue",
  "tatu", "tabacaria", "tamanho", "tatuagem", "trem",
  "uva", "universo", "ubuntu", "urso", "unha",
  "vender", "vacilo", "valeu", "vaca", "vidro",
  "xadrez", "xarope", "xenofobia", "xereta", "xaveco",
  "zebra", "zagueiro", "zero", "zoeira", "zoado"];

export default palavras;
